# Generated by Django 5.2.8 on 2025-11-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
    ]
