# Generated by Django 6.0 on 2025-12-24 14:42

from django.db import migrations

def create_base_categories(apps, schema_editor):
    """
    Creates a comprehensive set of default categories for all users.
    These categories have user_id set to NULL.
    """
    Category = apps.get_model('finance', 'Category')
    
    # =================================
    #  Base Expense Categories
    # =================================
    expense_categories = [
        # Housing & Utilities
        "Rent/Mortgage", "Property Taxes", "Home Insurance", "HOA Fees",
        "Electricity", "Gas/Heating", "Water", "Internet", "Phone Bill", "Home Maintenance",
        
        # Food & Dining
        "Groceries", "Restaurants", "Coffee Shops", "Bars/Alcohol", "Food Delivery",
        
        # Transportation
        "Gas/Fuel", "Public Transit", "Car Payment", "Car Insurance", "Car Maintenance", "Parking/Tolls", "Taxi/Rideshare",
        
        # Health & Wellness
        "Health Insurance", "Doctor & Dentist", "Pharmacy", "Gym/Fitness", "Therapy",
        
        # Personal Care
        "Haircut/Salon", "Skincare & Cosmetics",
        
        # Shopping & Entertainment
        "Clothing & Accessories", "Electronics", "Hobbies", "Books", "Streaming Services",
        "Movies/Concerts", "Vacation/Travel", "Gifts",
        
        # Family & Kids
        "Childcare", "Kids' Activities", "Tuition", "Pets",
        
        # Financial
        "Taxes", "Bank Fees", "Loan Repayments", "Charitable Donations",
        
        # Other
        "Miscellaneous"
    ]
    for cat_name in expense_categories:
        Category.objects.get_or_create(name=cat_name, defaults={'is_income': False, 'user': None})

    # =================================
    #  Base Income Categories
    # =================================
    income_categories = [
        "Salary/Wages", "Bonus", "Freelance/Side Hustle", "Business Income", 
        "Interest Income", "Dividends", "Rental Income", "Gifts Received", 
        "Refunds/Reimbursements", "Other Income"
    ]
    for cat_name in income_categories:
        Category.objects.get_or_create(name=cat_name, defaults={'is_income': True, 'user': None})

def delete_base_categories(apps, schema_editor):
    """
    Deletes the base categories. This is the reverse operation.
    """
    Category = apps.get_model('finance', 'Category')
    
    all_categories = [
        "Rent/Mortgage", "Property Taxes", "Home Insurance", "HOA Fees",
        "Electricity", "Gas/Heating", "Water", "Internet", "Phone Bill", "Home Maintenance",
        "Groceries", "Restaurants", "Coffee Shops", "Bars/Alcohol", "Food Delivery",
        "Gas/Fuel", "Public Transit", "Car Payment", "Car Insurance", "Car Maintenance", "Parking/Tolls", "Taxi/Rideshare",
        "Health Insurance", "Doctor & Dentist", "Pharmacy", "Gym/Fitness", "Therapy",
        "Haircut/Salon", "Skincare & Cosmetics",
        "Clothing & Accessories", "Electronics", "Hobbies", "Books", "Streaming Services",
        "Movies/Concerts", "Vacation/Travel", "Gifts",
        "Childcare", "Kids' Activities", "Tuition", "Pets",
        "Taxes", "Bank Fees", "Loan Repayments", "Charitable Donations",
        "Miscellaneous",
        "Salary/Wages", "Bonus", "Freelance/Side Hustle", "Business Income", 
        "Interest Income", "Dividends", "Rental Income", "Gifts Received", 
        "Refunds/Reimbursements", "Other Income"
    ]
    Category.objects.filter(user=None, name__in=all_categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_category_user"),
    ]

    operations = [
        migrations.RunPython(create_base_categories, delete_base_categories),
    ]
